// AUTO-GENERATED by xui_codegen.py — DO NOT EDIT
// Source: floater_fs_area_search.xml
// Regenerate: python3 scripts/xui-codegen/xui_codegen.py indra/newview/skins/default/xui/en/floater_fs_area_search.xml FSAreaSearchUI

#ifndef FSAREASEARCHUI_GEN_H
#define FSAREASEARCHUI_GEN_H

#include "fsscrolllistctrl.h"
#include "llbutton.h"
#include "llcheckboxctrl.h"
#include "llcombobox.h"
#include "lllineeditor.h"
#include "llpanel.h"
#include "llspinctrl.h"
#include "lltabcontainer.h"
#include "lltextbox.h"

struct FSAreaSearchUI
{
    LLTabContainer* area_searchtab {};
    FSScrollListCtrl* result_list {};
    LLButton* Refresh {};
    LLTextBox* counter {};
    LLCheckBoxCtrl* beacons {};
    LLTextBox* name_label {};
    LLTextBox* desc_label {};
    LLLineEditor* name_search {};
    LLLineEditor* description_search {};
    LLTextBox* owner_label {};
    LLTextBox* group_label {};
    LLLineEditor* owner_search {};
    LLLineEditor* group_search {};
    LLTextBox* creator_label {};
    LLTextBox* last_owner_label {};
    LLLineEditor* creator_search {};
    LLLineEditor* last_owner_search {};
    LLCheckBoxCtrl* regular_expression {};
    LLButton* search {};
    LLButton* clear {};
    LLTextBox* only_list {};
    LLCheckBoxCtrl* filter_locked {};
    LLCheckBoxCtrl* filter_physical {};
    LLCheckBoxCtrl* filter_phantom {};
    LLCheckBoxCtrl* filter_temporary {};
    LLCheckBoxCtrl* filter_attachment {};
    LLCheckBoxCtrl* filter_moap {};
    LLCheckBoxCtrl* filter_perm_copy {};
    LLCheckBoxCtrl* filter_perm_modify {};
    LLCheckBoxCtrl* filter_perm_transfer {};
    LLCheckBoxCtrl* filter_reflection_probe {};
    LLCheckBoxCtrl* filter_for_sale {};
    LLSpinCtrl* min_price {};
    LLTextBox* ui_and {};
    LLSpinCtrl* max_price {};
    LLTextBox* mouse_text {};
    LLComboBox* click_action {};
    LLCheckBoxCtrl* filter_distance {};
    LLSpinCtrl* min_distance {};
    LLTextBox* and2 {};
    LLSpinCtrl* max_distance {};
    LLCheckBoxCtrl* filter_agent_parcel_only {};
    LLCheckBoxCtrl* exclude_attachment {};
    LLCheckBoxCtrl* exclude_physical {};
    LLCheckBoxCtrl* exclude_temporary {};
    LLCheckBoxCtrl* exclude_reflection_probes {};
    LLCheckBoxCtrl* exclude_childprim {};
    LLCheckBoxCtrl* exclude_neighbor_region {};
    LLButton* apply {};
    LLButton* save_as_default {};
    LLTextBox* display_column {};
    LLCheckBoxCtrl* show_distance {};
    LLCheckBoxCtrl* show_name {};
    LLCheckBoxCtrl* show_description {};
    LLCheckBoxCtrl* show_price {};
    LLCheckBoxCtrl* show_land_impact {};
    LLCheckBoxCtrl* show_prim_count {};
    LLCheckBoxCtrl* show_owner {};
    LLCheckBoxCtrl* show_group {};
    LLCheckBoxCtrl* show_creator {};
    LLCheckBoxCtrl* show_last_owner {};
    LLCheckBoxCtrl* double_click_touch {};
    LLCheckBoxCtrl* double_click_buy {};
    LLCheckBoxCtrl* double_click_sit {};

    // Call this from your floater/panel's postBuild().
    // Returns false and logs an error if any required control is missing.
    bool postBuild(LLPanel* panel)
    {
        bool ok = true;
        area_searchtab = panel->getChild<LLTabContainer>("area_searchtab", /*recurse=*/true);
        if (!area_searchtab) { LL_WARNS() << "FSAreaSearchUI: missing control 'area_searchtab'" << LL_ENDL; ok = false; }
        result_list = panel->getChild<FSScrollListCtrl>("result_list", /*recurse=*/true);
        if (!result_list) { LL_WARNS() << "FSAreaSearchUI: missing control 'result_list'" << LL_ENDL; ok = false; }
        Refresh = panel->getChild<LLButton>("Refresh", /*recurse=*/true);
        if (!Refresh) { LL_WARNS() << "FSAreaSearchUI: missing control 'Refresh'" << LL_ENDL; ok = false; }
        counter = panel->getChild<LLTextBox>("counter", /*recurse=*/true);
        if (!counter) { LL_WARNS() << "FSAreaSearchUI: missing control 'counter'" << LL_ENDL; ok = false; }
        beacons = panel->getChild<LLCheckBoxCtrl>("beacons", /*recurse=*/true);
        if (!beacons) { LL_WARNS() << "FSAreaSearchUI: missing control 'beacons'" << LL_ENDL; ok = false; }
        name_label = panel->getChild<LLTextBox>("name_label", /*recurse=*/true);
        if (!name_label) { LL_WARNS() << "FSAreaSearchUI: missing control 'name_label'" << LL_ENDL; ok = false; }
        desc_label = panel->getChild<LLTextBox>("desc_label", /*recurse=*/true);
        if (!desc_label) { LL_WARNS() << "FSAreaSearchUI: missing control 'desc_label'" << LL_ENDL; ok = false; }
        name_search = panel->getChild<LLLineEditor>("name_search", /*recurse=*/true);
        if (!name_search) { LL_WARNS() << "FSAreaSearchUI: missing control 'name_search'" << LL_ENDL; ok = false; }
        description_search = panel->getChild<LLLineEditor>("description_search", /*recurse=*/true);
        if (!description_search) { LL_WARNS() << "FSAreaSearchUI: missing control 'description_search'" << LL_ENDL; ok = false; }
        owner_label = panel->getChild<LLTextBox>("owner_label", /*recurse=*/true);
        if (!owner_label) { LL_WARNS() << "FSAreaSearchUI: missing control 'owner_label'" << LL_ENDL; ok = false; }
        group_label = panel->getChild<LLTextBox>("group_label", /*recurse=*/true);
        if (!group_label) { LL_WARNS() << "FSAreaSearchUI: missing control 'group_label'" << LL_ENDL; ok = false; }
        owner_search = panel->getChild<LLLineEditor>("owner_search", /*recurse=*/true);
        if (!owner_search) { LL_WARNS() << "FSAreaSearchUI: missing control 'owner_search'" << LL_ENDL; ok = false; }
        group_search = panel->getChild<LLLineEditor>("group_search", /*recurse=*/true);
        if (!group_search) { LL_WARNS() << "FSAreaSearchUI: missing control 'group_search'" << LL_ENDL; ok = false; }
        creator_label = panel->getChild<LLTextBox>("creator_label", /*recurse=*/true);
        if (!creator_label) { LL_WARNS() << "FSAreaSearchUI: missing control 'creator_label'" << LL_ENDL; ok = false; }
        last_owner_label = panel->getChild<LLTextBox>("last_owner_label", /*recurse=*/true);
        if (!last_owner_label) { LL_WARNS() << "FSAreaSearchUI: missing control 'last_owner_label'" << LL_ENDL; ok = false; }
        creator_search = panel->getChild<LLLineEditor>("creator_search", /*recurse=*/true);
        if (!creator_search) { LL_WARNS() << "FSAreaSearchUI: missing control 'creator_search'" << LL_ENDL; ok = false; }
        last_owner_search = panel->getChild<LLLineEditor>("last_owner_search", /*recurse=*/true);
        if (!last_owner_search) { LL_WARNS() << "FSAreaSearchUI: missing control 'last_owner_search'" << LL_ENDL; ok = false; }
        regular_expression = panel->getChild<LLCheckBoxCtrl>("regular_expression", /*recurse=*/true);
        if (!regular_expression) { LL_WARNS() << "FSAreaSearchUI: missing control 'regular_expression'" << LL_ENDL; ok = false; }
        search = panel->getChild<LLButton>("search", /*recurse=*/true);
        if (!search) { LL_WARNS() << "FSAreaSearchUI: missing control 'search'" << LL_ENDL; ok = false; }
        clear = panel->getChild<LLButton>("clear", /*recurse=*/true);
        if (!clear) { LL_WARNS() << "FSAreaSearchUI: missing control 'clear'" << LL_ENDL; ok = false; }
        only_list = panel->getChild<LLTextBox>("only_list", /*recurse=*/true);
        if (!only_list) { LL_WARNS() << "FSAreaSearchUI: missing control 'only_list'" << LL_ENDL; ok = false; }
        filter_locked = panel->getChild<LLCheckBoxCtrl>("filter_locked", /*recurse=*/true);
        if (!filter_locked) { LL_WARNS() << "FSAreaSearchUI: missing control 'filter_locked'" << LL_ENDL; ok = false; }
        filter_physical = panel->getChild<LLCheckBoxCtrl>("filter_physical", /*recurse=*/true);
        if (!filter_physical) { LL_WARNS() << "FSAreaSearchUI: missing control 'filter_physical'" << LL_ENDL; ok = false; }
        filter_phantom = panel->getChild<LLCheckBoxCtrl>("filter_phantom", /*recurse=*/true);
        if (!filter_phantom) { LL_WARNS() << "FSAreaSearchUI: missing control 'filter_phantom'" << LL_ENDL; ok = false; }
        filter_temporary = panel->getChild<LLCheckBoxCtrl>("filter_temporary", /*recurse=*/true);
        if (!filter_temporary) { LL_WARNS() << "FSAreaSearchUI: missing control 'filter_temporary'" << LL_ENDL; ok = false; }
        filter_attachment = panel->getChild<LLCheckBoxCtrl>("filter_attachment", /*recurse=*/true);
        if (!filter_attachment) { LL_WARNS() << "FSAreaSearchUI: missing control 'filter_attachment'" << LL_ENDL; ok = false; }
        filter_moap = panel->getChild<LLCheckBoxCtrl>("filter_moap", /*recurse=*/true);
        if (!filter_moap) { LL_WARNS() << "FSAreaSearchUI: missing control 'filter_moap'" << LL_ENDL; ok = false; }
        filter_perm_copy = panel->getChild<LLCheckBoxCtrl>("filter_perm_copy", /*recurse=*/true);
        if (!filter_perm_copy) { LL_WARNS() << "FSAreaSearchUI: missing control 'filter_perm_copy'" << LL_ENDL; ok = false; }
        filter_perm_modify = panel->getChild<LLCheckBoxCtrl>("filter_perm_modify", /*recurse=*/true);
        if (!filter_perm_modify) { LL_WARNS() << "FSAreaSearchUI: missing control 'filter_perm_modify'" << LL_ENDL; ok = false; }
        filter_perm_transfer = panel->getChild<LLCheckBoxCtrl>("filter_perm_transfer", /*recurse=*/true);
        if (!filter_perm_transfer) { LL_WARNS() << "FSAreaSearchUI: missing control 'filter_perm_transfer'" << LL_ENDL; ok = false; }
        filter_reflection_probe = panel->getChild<LLCheckBoxCtrl>("filter_reflection_probe", /*recurse=*/true);
        if (!filter_reflection_probe) { LL_WARNS() << "FSAreaSearchUI: missing control 'filter_reflection_probe'" << LL_ENDL; ok = false; }
        filter_for_sale = panel->getChild<LLCheckBoxCtrl>("filter_for_sale", /*recurse=*/true);
        if (!filter_for_sale) { LL_WARNS() << "FSAreaSearchUI: missing control 'filter_for_sale'" << LL_ENDL; ok = false; }
        min_price = panel->getChild<LLSpinCtrl>("min_price", /*recurse=*/true);
        if (!min_price) { LL_WARNS() << "FSAreaSearchUI: missing control 'min_price'" << LL_ENDL; ok = false; }
        ui_and = panel->getChild<LLTextBox>("and", /*recurse=*/true);
        if (!ui_and) { LL_WARNS() << "FSAreaSearchUI: missing control 'and'" << LL_ENDL; ok = false; }
        max_price = panel->getChild<LLSpinCtrl>("max_price", /*recurse=*/true);
        if (!max_price) { LL_WARNS() << "FSAreaSearchUI: missing control 'max_price'" << LL_ENDL; ok = false; }
        mouse_text = panel->getChild<LLTextBox>("mouse_text", /*recurse=*/true);
        if (!mouse_text) { LL_WARNS() << "FSAreaSearchUI: missing control 'mouse_text'" << LL_ENDL; ok = false; }
        click_action = panel->getChild<LLComboBox>("click_action", /*recurse=*/true);
        if (!click_action) { LL_WARNS() << "FSAreaSearchUI: missing control 'click_action'" << LL_ENDL; ok = false; }
        filter_distance = panel->getChild<LLCheckBoxCtrl>("filter_distance", /*recurse=*/true);
        if (!filter_distance) { LL_WARNS() << "FSAreaSearchUI: missing control 'filter_distance'" << LL_ENDL; ok = false; }
        min_distance = panel->getChild<LLSpinCtrl>("min_distance", /*recurse=*/true);
        if (!min_distance) { LL_WARNS() << "FSAreaSearchUI: missing control 'min_distance'" << LL_ENDL; ok = false; }
        and2 = panel->getChild<LLTextBox>("and2", /*recurse=*/true);
        if (!and2) { LL_WARNS() << "FSAreaSearchUI: missing control 'and2'" << LL_ENDL; ok = false; }
        max_distance = panel->getChild<LLSpinCtrl>("max_distance", /*recurse=*/true);
        if (!max_distance) { LL_WARNS() << "FSAreaSearchUI: missing control 'max_distance'" << LL_ENDL; ok = false; }
        filter_agent_parcel_only = panel->getChild<LLCheckBoxCtrl>("filter_agent_parcel_only", /*recurse=*/true);
        if (!filter_agent_parcel_only) { LL_WARNS() << "FSAreaSearchUI: missing control 'filter_agent_parcel_only'" << LL_ENDL; ok = false; }
        exclude_attachment = panel->getChild<LLCheckBoxCtrl>("exclude_attachment", /*recurse=*/true);
        if (!exclude_attachment) { LL_WARNS() << "FSAreaSearchUI: missing control 'exclude_attachment'" << LL_ENDL; ok = false; }
        exclude_physical = panel->getChild<LLCheckBoxCtrl>("exclude_physical", /*recurse=*/true);
        if (!exclude_physical) { LL_WARNS() << "FSAreaSearchUI: missing control 'exclude_physical'" << LL_ENDL; ok = false; }
        exclude_temporary = panel->getChild<LLCheckBoxCtrl>("exclude_temporary", /*recurse=*/true);
        if (!exclude_temporary) { LL_WARNS() << "FSAreaSearchUI: missing control 'exclude_temporary'" << LL_ENDL; ok = false; }
        exclude_reflection_probes = panel->getChild<LLCheckBoxCtrl>("exclude_reflection_probes", /*recurse=*/true);
        if (!exclude_reflection_probes) { LL_WARNS() << "FSAreaSearchUI: missing control 'exclude_reflection_probes'" << LL_ENDL; ok = false; }
        exclude_childprim = panel->getChild<LLCheckBoxCtrl>("exclude_childprim", /*recurse=*/true);
        if (!exclude_childprim) { LL_WARNS() << "FSAreaSearchUI: missing control 'exclude_childprim'" << LL_ENDL; ok = false; }
        exclude_neighbor_region = panel->getChild<LLCheckBoxCtrl>("exclude_neighbor_region", /*recurse=*/true);
        if (!exclude_neighbor_region) { LL_WARNS() << "FSAreaSearchUI: missing control 'exclude_neighbor_region'" << LL_ENDL; ok = false; }
        apply = panel->getChild<LLButton>("apply", /*recurse=*/true);
        if (!apply) { LL_WARNS() << "FSAreaSearchUI: missing control 'apply'" << LL_ENDL; ok = false; }
        save_as_default = panel->getChild<LLButton>("save_as_default", /*recurse=*/true);
        if (!save_as_default) { LL_WARNS() << "FSAreaSearchUI: missing control 'save_as_default'" << LL_ENDL; ok = false; }
        display_column = panel->getChild<LLTextBox>("display_column", /*recurse=*/true);
        if (!display_column) { LL_WARNS() << "FSAreaSearchUI: missing control 'display_column'" << LL_ENDL; ok = false; }
        show_distance = panel->getChild<LLCheckBoxCtrl>("show_distance", /*recurse=*/true);
        if (!show_distance) { LL_WARNS() << "FSAreaSearchUI: missing control 'show_distance'" << LL_ENDL; ok = false; }
        show_name = panel->getChild<LLCheckBoxCtrl>("show_name", /*recurse=*/true);
        if (!show_name) { LL_WARNS() << "FSAreaSearchUI: missing control 'show_name'" << LL_ENDL; ok = false; }
        show_description = panel->getChild<LLCheckBoxCtrl>("show_description", /*recurse=*/true);
        if (!show_description) { LL_WARNS() << "FSAreaSearchUI: missing control 'show_description'" << LL_ENDL; ok = false; }
        show_price = panel->getChild<LLCheckBoxCtrl>("show_price", /*recurse=*/true);
        if (!show_price) { LL_WARNS() << "FSAreaSearchUI: missing control 'show_price'" << LL_ENDL; ok = false; }
        show_land_impact = panel->getChild<LLCheckBoxCtrl>("show_land_impact", /*recurse=*/true);
        if (!show_land_impact) { LL_WARNS() << "FSAreaSearchUI: missing control 'show_land_impact'" << LL_ENDL; ok = false; }
        show_prim_count = panel->getChild<LLCheckBoxCtrl>("show_prim_count", /*recurse=*/true);
        if (!show_prim_count) { LL_WARNS() << "FSAreaSearchUI: missing control 'show_prim_count'" << LL_ENDL; ok = false; }
        show_owner = panel->getChild<LLCheckBoxCtrl>("show_owner", /*recurse=*/true);
        if (!show_owner) { LL_WARNS() << "FSAreaSearchUI: missing control 'show_owner'" << LL_ENDL; ok = false; }
        show_group = panel->getChild<LLCheckBoxCtrl>("show_group", /*recurse=*/true);
        if (!show_group) { LL_WARNS() << "FSAreaSearchUI: missing control 'show_group'" << LL_ENDL; ok = false; }
        show_creator = panel->getChild<LLCheckBoxCtrl>("show_creator", /*recurse=*/true);
        if (!show_creator) { LL_WARNS() << "FSAreaSearchUI: missing control 'show_creator'" << LL_ENDL; ok = false; }
        show_last_owner = panel->getChild<LLCheckBoxCtrl>("show_last_owner", /*recurse=*/true);
        if (!show_last_owner) { LL_WARNS() << "FSAreaSearchUI: missing control 'show_last_owner'" << LL_ENDL; ok = false; }
        double_click_touch = panel->getChild<LLCheckBoxCtrl>("double_click_touch", /*recurse=*/true);
        if (!double_click_touch) { LL_WARNS() << "FSAreaSearchUI: missing control 'double_click_touch'" << LL_ENDL; ok = false; }
        double_click_buy = panel->getChild<LLCheckBoxCtrl>("double_click_buy", /*recurse=*/true);
        if (!double_click_buy) { LL_WARNS() << "FSAreaSearchUI: missing control 'double_click_buy'" << LL_ENDL; ok = false; }
        double_click_sit = panel->getChild<LLCheckBoxCtrl>("double_click_sit", /*recurse=*/true);
        if (!double_click_sit) { LL_WARNS() << "FSAreaSearchUI: missing control 'double_click_sit'" << LL_ENDL; ok = false; }
        return ok;
    }
};

#endif // FSAREASEARCHUI_GEN_H
